### ISSUE TITLE
Potential to cause issue by hard-coding release name

### ISSUE THREAD

**Issue by JeffMatson** [QROkes/webinoly#1]
https://github.com/QROkes/webinoly/blob/13d9025391ae8453bae8946f21bde1e64ddfa72d/lib/general#L65

This assumes they're running Xenial, but they could be running other flavors. Might be a good idea to detect this and set dynamically.

The repo source could probably be better too. Something more well-known?

**Comment by QROkes** [comment]
Yes, you are right. Ubuntu 16.04 is the only distribution supported by Webinoly at this moment and is well documented. I thought about detect the distribution before do the installation, but I decided to put the Warning in the front page of Github project and Webinoly Website.
MariaDB repo is an official repo suggested by the official site of MariaDB.

**Comment by QROkes** [comment]
Fixed in v1.1.0
