### ISSUE TITLE
Dedicated user and php-fpm pool for each website

### ISSUE THREAD

**Issue by nhanledev** [QROkes/webinoly#10]
Hello,

I think the script should let each website run on a different user and php-fpm pool for security purpose.

It's also nice to have new user created and setup for each new website when it had been added.

**Comment by QROkes** [comment]
It makes sense in shared hosting environments, but I'm not sure what would be the benefits in VPS environment.

**Comment by QROkes** [comment]
- All of those websites in a VPS are usually managed by the same owner. What do you want to hide from one site to another that are both yours?
- In shared hosting makes easier the resource management for each user, in a VPS is the same, all the resources are all for you.

Maybe I'm missing or not seeing some thing!

**Comment by nhanledev** [comment]
- When a single website on VPS got hacked, it could have malicious codes uploaded. Other websites could be affected because the code can read all files which have the same permission.

- I see your script blocked the direct access to php files inside wp-content/upload. It may help protect WordPress websites but what about other scripts? Does implementing the same protection method help to prevent malicious code from running?

**Comment by QROkes** [comment]
Yes, I understand your point, and yes, it will be a little bit more secure if we have dedicated users. But, not sure if it worth it, or not sure how implement it to be optional, because not all the people want to create and remember a user for each website.

And believe me, if someone want to hack your site/server, having dedicated users will not stop the to these guys, maybe it will be one minute more to do it.

**Comment by nhanledev** [comment]
Yes, I understand the point that it may be overkill to have a user for each site. I just want to add a little extra layer but if it is not worth to have, I think I should just ignore it :)

Thank you a lot! 👍

**Comment by QROkes** [comment]
I will leave this ticket open to think about it.
Maybe in the future!

Thanks for sharing your ideas and opinion with us.

**Comment by devbhosale** [comment]
@QROkes  +1 for this feature as well. it will very useful to provide that flexibility to those want to use this in a managed shared environment... also, it will make sure a dedicated pool of fpm resources is always available per site...

**Comment by QROkes** [comment]
@devbhosale Send me a Pull Request.

**Comment by QROkes** [comment]
After an extensive revision and discussion of this "issue":

Webinoly is not a “shared hosting management tool” and it’s not in our plans.

You should **be careful** of any tool or solution offering this feature with NGINX, most of them (all I've seen) are using a third-party open-source NGINX module to avoid paying for NGINX Plus (not free), which is completely **unethical** (don't you think?), also these modules (FRiCKLE and Torden fork) have not been updated or maintained for years, for what is completely **unsafe** to use them.

Also, if isolation is a concern for you for any reason, the best way to achieve this is by having an individual VPS for each site. Nowadays, you can get a VPS with a top-notch cloud provider for as low as $2 per month, so this shouldn't be a problem.

**Comment by starnetwork** [comment]
Agree with your words, Webinoly is not a shared hosting, but:
1. Security: someone can put few website, this will help to Improve security and prevent mistakes
2. flexibility: possibility to give for example developer access only to the clone without "touch" the production

Please re-consider it.
Thanks!
