### ISSUE TITLE
[Feature request] Reset permission of all files to default and many more

### ISSUE THREAD

**Issue by nhanledev** [QROkes/webinoly#11]
Hello, after a few weeks using the script, I found that it would be very nice to have some additional features like:

- `reset-owner` and `reset-permission` to reset the owner and permission of all files to www-data:www-data and 755 for the folders, 644 for the files when we encountered the permission problem (by modifying stuff with other users).
- Will the script support customized but widely-used WordPress stacks like BedRock in the future? 
- It would be also very nice If the installation script warns me to configure the firewall and print out the port IN and OUT that the server need to be set for reference, too.
- The cache clearing will print a lot of errors when I do the clearing after disabled the memcached by removing it out of the server. It should handle that error more gracefully :)

Thank you for such a nice script!

**Comment by QROkes** [comment]
In the same order:

- Ok. I will add it to the list of possible features, I don't know when will be included and released.

- That kind of tools are totally out of scope of this project, Webinoly is focused on server side optimization, not in web dev.

- Ok, I agree that it could be improved and add this info or maybe a link to the complete documentation. I will think about it, but definitely I will do something to improve it.

- I will try to reproduce this issue and fix it.

**Thanks a lot for your very valuable feedback.**

**Comment by mrzhoul-2** [comment]
So... there is problem with permission? I found this script and it works flawlessly.
https://gist.github.com/Adirael/3383404
https://github.com/rubo77/fix-wordpress-permissions.sh/blob/master/fix-wordpress-permissions.sh

**Comment by nhanledev** [comment]
> So... there is problem with permission? I found this script and it works flawlessly.
> https://gist.github.com/Adirael/3383404
> https://github.com/rubo77/fix-wordpress-permissions.sh/blob/master/fix-wordpress-permissions.sh

It was not like a problem, but since everyone often uses different user account to upload files via SSH, and the webserver needs all files to be owned by www-data by default to work correctly, I think it would be nice to have a built-in tool to reset the owner or/and permission.

I always use the chown and chmod commands to fix the permission after uploading new files. It works for me so far.

**Comment by QROkes** [comment]
This is scheduled to be included in Webinoly in the next release (v1.11.2), it will be integrated in the `-server-reset` command. And be careful with the scripts you shared before, 775 and 664 are not the best in WP.

**Comment by QROkes** [comment]
This feature is now integrated into `-server-reset`, released in v1.11.2.
