### ISSUE TITLE
Cache max_size and /run size

### ISSUE THREAD

**Issue by Elmolesto** [QROkes/webinoly#19]
I've an issue last week implementing webinoly on production site.
After the installation and configuration of a WP site on Ubuntu 18.04 (AWS Lightsail - 4GB RAM - 2cores) all gone right, but 30hs after (aprox) the webserver could't conect to external services via curl nor wget. I realized that rebooting the server the problem was solved, so i've figured it out that the problem was a misconfiguration in the server.

### The issue
Nginx max_cache was setted at 768mb and the /run have 400mb (where the ngingx cache stores). When the /run was out of space, the server could't execute curl nor wget commands, so rebooting the server cleans the /run.

### Solution
The size of /run is setted by ubuntu and the value is calculated as the 10% of the RAM size.
So i've mannualy change the max_cache to 256mb, but maybe Webinoly have to do it automatically and set it up as the 5% of RAM amount.

**Comment by QROkes** [comment]
Interesting point!

Actually, Nginx max_cache is a dynamic value based on the available RAM size, Webinoly calculate and set this value after installing Nginx as part of the "smart" optimization process.

What honestly, I didn't know is that Ubuntu limit the size of "/run" folder. Do you know where can I found the documentation about this topic?
This way I can better improve the way Webinoly calculates this value.

**Comment by Elmolesto** [comment]
Yes, /run is a tmpfs mounted when the vm boot, so the size is fixed; with "df -h" you can see the actual size.
Here you can read a bit more: https://askubuntu.com/questions/855740/how-do-i-increase-size-of-per-user-tmpfs-partition-run-user-id

As the user says, in "/etc/systemd/logind.conf" you can edit the line "RuntimeDirectorySize=10%" to the value you want.

**Comment by QROkes** [comment]
Fixed and released in v1.9.0.
