### ISSUE TITLE
main site redirecting to another

### ISSUE THREAD

**Issue by CharanjeetE** [QROkes/webinoly#21]
Hi 
I have two wordpress sites and I am using webinoly.My second site is redirecting to first site.Please let me know what I am missing or doing wrong.

**Comment by QROkes** [comment]
I tried to reproduce this issue but everything is working fine here.
Can you please tell me the steps to reproduce it, maybe is an specific configuration that is causing this issue.

**Comment by CharanjeetE** [comment]
Thanks QROkes/webinoly it is solved now.It was some problem in database.
