### ISSUE TITLE
[Feature Request] Mobile Caching

### ISSUE THREAD

**Issue by nhanledev** [QROkes/webinoly#22]
I am using some plugin that has separate configurations for Desktop and Mobile view. The issue here is Webinoly only cache the first visit, and it causes page break on Mobile if Desktop version was cached and vice versa.

I did some research and found some ways to include an additional parameter to cache pages on desktop and mobile separately. I can edit the config file to make it works, but I hope Webinoly should consider adding this feature to support the mobile caching better.

Thanks.

https://miteshshah.github.io/linux/nginx/how-to-setup-separate-nginx-fastcgi-cache-for-mobile-and-desktop-users/

**Comment by QROkes** [comment]
Thanks for your suggestion!
Most of the "modern" sites are using "responsive design", so I don't really think we need this kind of features.

**Comment by nhanledev** [comment]
I agree that most of the sites today are made responsively and this feature may be not as important as others. I am still using some plugin that has options for different devices to render directly on the server side, so I hope there will be an option for this feature in the future.

**Comment by QROkes** [comment]
Very particular and limited use case, modern websites don't use this approach, also this goes against best practices.
