### ISSUE TITLE
Third-Party SSL Certificates?

### ISSUE THREAD

**Issue by Jonathan-Garber** [QROkes/webinoly#23]
I am not seeing any method for adding Third-Party SSL Certs? Do I need to do these manually?

On EasyEngine for example, I will tell it to use a self-signed certificate then just replace the key/cert files with my real cert. It did all the configuration for me automatically. This makes it convenient.

**Comment by QROkes** [comment]
This feature is already developed and in "beta testing" phase, scheduled to be released in a couple of weeks. And yes, you can always do it manually.

Please, you are free to use any other tool you think is more convenient for you.

**Comment by QROkes** [comment]
@NanoG6 Please, read the documentation before asking!
This feature was included and released a year ago.

**Comment by NanoG6** [comment]
Ah I'm sorry, I didn't asking clear enough, my bad. What I was meant is there any command to generate self-signed certificate, maybe useing -ssl=self? Because my website is behind nginx reverse proxy which provide the SSL.
