### ISSUE TITLE
-verify fails when -default-site=blackhole | Clean Ubuntu 18.04 Install

### ISSUE THREAD

**Issue by Jonathan-Garber** [QROkes/webinoly#25]
```
sudo webinoly -default-site=blackhole
```
-- Results
```
Generating a 2048 bit RSA private key
.........................................+++
....+++
writing new private key to '/etc/ssl/private/webinoly-blackhole.key.pem'
-----
Blackhole Nginx site was successfully assigned as default site!
```

Now run 
```
sudo webinoly -verify
```
-- Results
```
Verifying integrity of the entire Webinoly system...

[INFO] File: /etc/nginx/.htpasswd not found!
[WARNING] Default site not found or is not enabled!

********************************************************************************
***************************
********      [ W A R N I N G ] System seems to be corrupted and could not work
properly        ***********
********************************************************************************
***************************
```

**Comment by QROkes** [comment]
**Please, stop opening new issues here.**
Everything is working fine in Webinoly, if you don't know how to use it, please read the documentation and tutorials available in our site before asking for help.

**Comment by Jonathan-Garber** [comment]
This was a 100% clean install of Ubuntu 18.04.2 and Webinoly. There were absolutely no changes or customizations on the OS.

Immediately after the webinoly install I ran the command to set the default site to blackhole as per documentation. Then ran verify and it produced the results you see here.

So how is that not a bug? May not be a show stopping but and cosmetic only but it is a bug.

**Comment by Jonathan-Garber** [comment]
Also a heads up since you don't like new "issues" being created.

Upon clean install of Webinoly on Ubuntu 18.04.2 where the directions specifically state to record the MySQL Root and Admin Passwords. Which I did record them as per instructions.

Those passwords however do not work and are not the correct passwords. Cannot use either one to access MySQL from command line or PMA Oh, but they do match the info from webinoly -info.

However the command Webinoly -dbpass does show the correct passwords and those do work.
So is that not a bug too? Maybe I am missing something there as well?

When using Webinoly -info and I see mysql-root and mysql-admin passwords are those not supposed to be the correct ones for accessing MySQL and PMA?

Why do they not match what I see in Webinoly -dbpass command?
Are they supposed to be two different things. The documentation doesn't clarify if they are.
