### ISSUE TITLE
[Request] SEOPress native integration

### ISSUE THREAD

**Issue by kksnow** [QROkes/webinoly#27]
Hi, Thank you for your awesome work. I would like to ask if it's possible to have native support for SEOPress in nginx conf.
Currently, i have to add all the code below manually for each website.

## >>> /etc/nginx/sites-available/site.conf
location ~ ([^/]*)sitemap(.*)\.x(m|s)l$ {              
                        ## SEOPress
                        rewrite ^/sitemaps\.xml$ /index.php?seopress_sitemap=1 last;
                        rewrite ^/sitemaps/news.xml$ /index.php?seopress_news=$1 last;
                        rewrite ^/sitemaps/video.xml$ /index.php?seopress_video=$1 last;
                        rewrite ^/sitemaps_xsl\.xsl$ /index.php?seopress_sitemap_xsl=1 last;
                        rewrite ^/sitemaps/([^/]+?)-sitemap([0-9]+)?.xml$ /index.php?seopress_cpt=$1&seopress_paged=$2 last;
                    }

## >>> /etc/nginx/common/locations.conf
location = /robots.txt {
                        allow all;
                        log_not_found off;
                        access_log off;
                        ##SEOPress
                        rewrite ^/robots\.txt$ /index.php?seopress_robots=1 last;
                    }

Hope you can do something about it. Thank you again for your time.

**Comment by QROkes** [comment]
If you don't want to do it manually, you can automate this task with the Internal-API to add this code every time a site is created.
