### ISSUE TITLE
Wrong PPA for NGINX Mainline branch

### ISSUE THREAD

**Issue by knytl** [QROkes/webinoly#29]
I found that "-mainline" is adding wrong PPA for mainline branch of NGINX.

Now adds: `https://launchpad.net/~nginx/+archive/ubuntu/development`

but mainline is now on: `https://launchpad.net/~nginx/+archive/ubuntu/mainline`

**Comment by QROkes** [comment]
Thanks for notifying me.
You are right and it will be fixed in the next release v1.10.1.
