### ISSUE TITLE
Directly modifying fstab sounds like disaster

### ISSUE THREAD

**Issue by JeffMatson** [QROkes/webinoly#3]
https://github.com/QROkes/webinoly/blob/13d9025391ae8453bae8946f21bde1e64ddfa72d/lib/install#L90

Directly modifying and core files (especially fstab) sounds disastrous. A better solution might be to at least make a backup first. Optimally, not touching it at all.

**Comment by QROkes** [comment]
I understand, but I think in this specific case it's totally secure, I'm just unmounting the folder used for FastCgi Cache when Nginx is purged. This folder is not mounted by default.

**Comment by QROkes** [comment]
There is no risk in this task!
