### ISSUE TITLE
Redirection manager not working

### ISSUE THREAD

**Issue by d-vo** [QROkes/webinoly#31]
First of all, thanks for all the effort put into this tool. I came across an issue with the new redirection manager feature: I have a main site example.com which I want to redirect to a subdomain: my.example.com. I try to achieve this by issuing the command: 

`sudo site example.com -redirection`
but this results in:
`[ERROR] Site example.com doesn't exists, please enter a valid domain name!`

Also something like 
`sudo site example.com -redirection -from=/ -to=https://my.example.com`
results in the same error. I also tried to create the example.com as an empty html page. But also no luck. Would be great to have some feedback regarding this issue.

**Comment by QROkes** [comment]
Your site _example.com_ must exist and be hosted on the same server. You can run _sudo site -list_, do you see _example.com_ listed?

**Comment by QROkes** [comment]
This ticket is now closed after a month with no response from the author.
