### ISSUE TITLE
How to use brotli instead of gzip?

### ISSUE THREAD

**Issue by sanjayojha** [QROkes/webinoly#32]
Hi love your stack. I want to know if there is an option of using brotli compression rather than default gzip?
I couldn't find any mention in documentation. 

I am going to test it on aws

**Comment by QROkes** [comment]
Please, read the docs to see all the [details about the packages included in Webinoly](https://webinoly.com/en/documentation/stacks/). We only use official and well-known packages and sources and unfortunately, none of them have included brotly with Nginx.

There's always some public unofficial Nginx compiled versions you can find in Google, or you can compile your own Nginx and use it in your own stack.

**Comment by sanjayojha** [comment]
Brotli is getting popular and give better compression than gzip, many stack has started supporting it with nginx. I know I can compile with my own Nginx. But since webinoly is about speed and performance. It is better to provide it as an alternative (just like wordops)  of gzip.

Just a mild suggestion

**Comment by QROkes** [comment]
Thanks for your suggestion, but Webinoly is not focused on early-adopters market and as I mentioned before, we only use official and well-known packages and sources, that means that we have no control on the modules included on these packages, also we are completely transparent about what we include in our stack, that means that we never compile or re-compile these packages.

I'm pretty sure that Brotly will be included in the future, but I don't know when. Last time I read a discussion about this topic, the official Ubuntu security team found a lot of issues and it was considered not mature enough to be included.

Webinoly is an Enterprise-Grade tool and that means we have a serious commitment with all our users about what we include in our stack.
