### ISSUE TITLE
Domain forwarding not working

### ISSUE THREAD

**Issue by zietbukuel** [QROkes/webinoly#35]
When I try to forward a domain, it doesn't let me. Here's the command I'm running:

`site mail.mydomain.com -forward=mail.mydomain.cloud -root=on`

I get thw following error:
`[ERROR] Invalid destination domain!`

I know these are technically not domains, but subdomains, so maybe that's why it's happening. But it would be nice to redirect "anything" to "anywhere".

Another thing I'd like to do is redirect a domain or subdomain to a domain with a path. Example:

domain1.com -> domain2.com/news

Thanks.

**Comment by QROkes** [comment]
Sorry, documentation has been updated now.
You need to add the scheme before the destination URL.

`sudo site example.com -forward=https://example.org`
