### ISSUE TITLE
Domain incorrectly considered to be a subdomain

### ISSUE THREAD

**Issue by Cerdtruir** [QROkes/webinoly#36]
Hi

When using the co.za tld i get an error saying that i am using a subdomain.

For example i cant force redirection to non www sites. i get this error: 

[ERROR] Please, use the main/root domain, Force-Redirection should not be used in Subdomains!

Is there a workaround for this in the meantime

Thanks

**Comment by QROkes** [comment]
I need to investigate this issue, "co.za" TLD is already included in Webinoly as valid, so that error shouldn't be happening.

In the meantime you can always pass the `-subdomain=false` option to force some behavior, maybe you should also do it when the site is created.

**Comment by Cerdtruir** [comment]
> I need to investigate this issue, "co.za" TLD is already included in Webinoly as valid, so that error shouldn't be happening.
> 
> In the meantime you can always pass the `-subdomain=false` option to force some behavior, maybe you should also do it when the site is created.

Thanks for the reply

The -subdomain=false flag worked for the www redirect

My site is already up and running is there a way of editing the site with this flag instead of recreating it. I did get the subdomain error when i created the site initially, what does webinoly do when it detects a subdomain? What are the downsides?

**Comment by QROkes** [comment]
Don't worry, server_names in Nginx has been automatically fixed after you forced the www redirection, that's the important part, you don't need to rebuild your site. Just remember to use the subdomain option if you need an SSL cert. This will be fixed in the next release (v1.11.1).

**Comment by QROkes** [comment]
Just for the record!
This issue was caused due to a very peculiar situation, we have just found out that:

- .co.za (valid)
- .net.za (valid)
- .org.za (valid)
- .web.za (valid)
- .za (invalid and not even exists alone, you can not buy example.za)

That small detail was breaking our algorithm.

**Comment by Cerdtruir** [comment]
> Don't worry, server_names in Nginx has been automatically fixed after you forced the www redirection, that's the important part, you don't need to rebuild your site. Just remember to use the subdomain option if you need an SSL cert. This will be fixed in the next release (v1.11.1).

Thanks, everything is working well now.

**Comment by QROkes** [comment]
Fixed in Webinoly v1.11.1, released today.
