### ISSUE TITLE
HTTPAUTH is not working

### ISSUE THREAD

**Issue by vasyablack** [QROkes/webinoly#37]
HTTPAUTH is not working in global mode.
But works well when use `httpauth example.com -wp-admin=on ` command.

**Comment by vasyablack** [comment]
Even in last update v1.11.1

**Comment by QROkes** [comment]
Global users are disabled when you have created per site users.

**Comment by vasyablack** [comment]
I've just try to
- Disable httpauth per sites
- Delete httpauth user
- Enable httpauth global
- Create new user
And it's still doesn't work

**Comment by vasyablack** [comment]
Before do that I has only one user and it was global.

**Comment by QROkes** [comment]
Please, read the documentation.
If you find any issues, please provide technical details.

**Comment by vasyablack** [comment]
Just check NGINX configuration files in `/etc/nginx/sites-available/domain.com` and find include directive `include common/wpcommon-noauth.conf;` and the same for all my sites, but I enabled httpauth by `httpauth -wp-admin=on`

**Comment by QROkes** [comment]
Documentation is very clear:

> if you need to enable/disable (on/off) the HTTP Authentication in WordPress login pages, you can use the following command **and every site created after that will take this setting.**
>` sudo httpauth -wp-admin=off`
> To enable/disable (on/off) this feature in an existing site:
> `sudo httpauth example.com -wp-admin=off`

**Comment by vasyablack** [comment]
Ooops! Now I understand, sorry!
