### ISSUE TITLE
sudo webinoly -tools-site=sub.domain.tld creates error when using wildcard certs

### ISSUE THREAD

**Issue by garikaib** [QROkes/webinoly#39]
So I created a site **example.com** and issued a Wildcard certificate. I then created another site **sub.example.com**. And I added it to the wildcard certificate. That went well. I wanted to make sure that tools on port 22222 are only accessible on the subdomain.
`sudo webinoly -tools-site=sub.example.com`

This creates an error in Nginx as it fails to ascertain the fact that the domain isn't pointing to a site specific certificate. It creates TLS entries pointing to non-existant certs in Nginx. The result is a configuration failure.
**Possible solutions**

1. Find a way to keep record of type of certs issued and point to wildcard instead of entries pointing to non-existant certs
2. When a site is added to a wildcard, add symlinks that makes what would be site-specific certs point to wildcard files instead.

Solution two is cleaner and would create less headaches I think. Naturally, there should be a way to clean up and delete the link if we delete the site for example.

**Comment by QROkes** [comment]
Can you please provide the details:

- Where the tools-site Nginx TLS entries are pointing?
- Are these entries are different compared with the sub.example.com Nginx conf file?
- Can you please describe the steps to reproduce this issues?

**Comment by garikaib** [comment]
1. The tool site entries were pointing to /etc/letsencrypt/live/sub.example.com/fullchain.pem
2. TLS entries for actual sub are different. They rightly point to the wildcard at /etc/letsencrypt/live/example.com/fullchain.pem
3. On a pristine Ubuntu 18.04
 a) Install webinoly
b) Create wp site example.com
c) Turn ssl on using wildcard on example.com
d) Create site sub.example.com
e) Add site to wildcard certificate
f) Make sub.example.com the tools domain
**Result**
nginx -t fails as webinoly automatically configures TLS by trying to point to nonexistent sub.example folder under letsencrypt

**Comment by QROkes** [comment]
Ok, now I understand!
Thanks for reporting this issue.

This means it will fail with wildcard certs and also when a custom (non-le) cert is used.
**It will be fixed in v1.12.1.**

**Comment by QROkes** [comment]
This issue has been fixed in Webinoly v1.12.1 released today.
