### ISSUE TITLE
Creating and modifying swap files

### ISSUE THREAD

**Issue by JeffMatson** [QROkes/webinoly#4]
https://github.com/QROkes/webinoly/blob/13d9025391ae8453bae8946f21bde1e64ddfa72d/lib/install#L649

This seems dangerous and could lead to conflicts.

**Comment by QROkes** [comment]
Webinoly creates a Swap Partition if not exist, when Webinoly is uninstalled it removes this partition.
I see I can improve this, detecting if swap was created by Webinoly and then remove it. If Swap was created previously by the user (not Webinoly), then we should not remove it.
What do you think?

**Comment by QROkes** [comment]
Fixed in v1.1.0
