### ISSUE TITLE
www to non-www in subdomian

### ISSUE THREAD

**Issue by dimtelecom** [QROkes/webinoly#42]
Hi.
I have a redirect problem.
I created a domain with the command
```
> site dev.mysite.com -wp -cache=on -wp-cache-plugins=on
> site dev.mysite.com -ssl=on
> site dev.mysite.com  -info
```

> Type: WordPress
> Status: Enabled
> SSL: Let's Encrypt
> Access Logs: false
> Force Redirect: off
> Size: 776M
> 
> Cache: true
> Multisite: false
> WP Auth: true
> Debug: false
> 
> Database: localhost
> DB Name: wp_mysite_com
> DB User: wp_mysite_com
> DB Prefix: wp_

After that I checked redirect:
http://dev.mysite.com ---> https://dev.mysite.com -> OK
https://www.dev.mysite.com ---> https://dev.mysite.com -> OK
http://www.dev.mysite.com ---> https://dev.mysite.com -> NOT OK. It shows me "Welcome to nginx!" Page

I can't use force-redirect option for subdomain
```
> site dev.mysite.com -force-redirect=root
[ERROR] Please, use the main/root domain, Force-Redirection should not be used in Subdomains!
```

**Comment by QROkes** [comment]
I think the error message is very clear.

**Comment by dimtelecom** [comment]
> I think the error message is very clear.

Does this mean that I cannot use https for subdomains?
Sorry, but maybe I misunderstand the error message
