### ISSUE TITLE
MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING

### ISSUE THREAD

**Issue by baiyuanlab** [QROkes/webinoly#43]
Hi,

When using Firefox to browse the site command established website, a MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING problem will appear. The temporary solution is to add two parameters to /etc/nginx/sites-available/example.com as follows:

`resolver 8.8.8.8 1.1.1.1 valid=300s;`
`resolver_timeout 5s;`

Could this problem be solved in the next version?

looking forward to your reply.

**Comment by QROkes** [comment]
Sorry, but we can not implement the fix you are suggesting.

Your issue is related to an OCSP failure that happens with some browsers and Nginx, seems like some configurations are not ready for the "must-staple" option that we use in Let's Encrypt certs.

**Comment by baiyuanlab** [comment]
> Sorry, but we can not implement the fix you are suggesting.
> 
> Your issue is related to an OCSP failure that happens with some browsers and Nginx, seems like some configurations are not ready for the "must-staple" option that we use in Let's Encrypt certs.

Okay, I got it.

**Comment by QROkes** [comment]
@baiyuanlab Just as a reference, here is a good explanation of this issue: https://blog.cloudflare.com/high-reliability-ocsp-stapling/ 

Webinoly always uses the "OCSP must-staple" option for Let's Encrypt certs.
It's the better option but some browsers and even Nginx still have some improvement areas on this topic.
