### ISSUE TITLE
Setting fastcgi_read_timeout

### ISSUE THREAD

**Issue by wpjames** [QROkes/webinoly#44]
I was getting some 504 errors when trying to import template sites into Wordpress. I eventually got it to work by changing fastcgi_read_timeout to a higher value in /etc/nginx/conf.d/fastcgi.conf.

I noticed that the default value in NGINX is 60s but you have it set to 30s. Any reason for hard coding it as 30s?

What is the best way of changing fastcgi_read_timeout without manually editing /etc/nginx/conf.d/fastcgi.conf?

**Comment by QROkes** [comment]
30 seconds are enough for most of the normal use cases, however of course you can manually increase this value according to your needs. Actually, is planned in the next release (v1.14.0), that `fastcgi_read_timeout` should be aligned with PHP `max_execution_time`, the latter can be customized by adjusting one value in Webinoly conf file.
