### ISSUE TITLE
Support of Wordpress Applications Passwords

### ISSUE THREAD

**Issue by laurentdiazfr** [QROkes/webinoly#45]
Wordpress 5.6 introduces a new way to communicate with its REST API called [Applications Passwords](https://make.wordpress.org/core/2020/11/05/application-passwords-integration-guide/).

It seems Webinoly is not compatible with this feature. 

I always get the message **Your website appears to use Basic Authentication, which is not currently compatible with Application Passwords** even if I deactivate httpauth.
 
![image](https://user-images.githubusercontent.com/39262459/102335246-ef253b80-3f8f-11eb-945d-612a061e4260.png)

**Comment by QROkes** [comment]
Just follow the indications in the error message, HTTP Authentication needs to be disabled if you want to use the "Application Password".

As a security measure, Webinoly has HTTP Auth enabled by default for WP, please, read the documentation, when auth is disabled the next time you logged in in WP the error message should be gone.

**Comment by laurentdiazfr** [comment]
Thanks for your quick response but as I wrote in my message, I deactivated httpauth.

I used these commands :
1. sudo httpauth mydomain.com -wp-admin=off
2. sudo httpauth mydomain.com -delete=myuser

It works but still the message is there.

**Comment by QROkes** [comment]
1. sudo httpauth mydomain.com -wp-admin=off
2. Logout from WP
3. Try to login again and auth will not be required (because is now disabled), also the app password message should not be there. Just to be sure, try to login in a different browser!

**Comment by laurentdiazfr** [comment]
Step 3 was the solution.
Indeed if I change my browser or use private mode it works !
