### ISSUE TITLE
How to change current site type from PHP to Wordpress?

### ISSUE THREAD

**Issue by jhuyvu** [QROkes/webinoly#47]
I created site by sudo site domain -php -mysql and restore wordpress source code.
But after run -clone-from new site still using old datababse config.
Please help me
* My English is not good, hope you guys can understand my problem.

**Comment by QROkes** [comment]
Please, read the docs!
This is not an issue, if you have a support question, please use the community forum.
You can not use multiple types of sites when creating a site, also that's why WP type of site exists.

**Comment by jhuyvu** [comment]
Solved!
sudo site domain.com -wp
and replace created wp site with my wordpress code :)
