### ISSUE TITLE
Feature: Transparently serve converted WebP images instead of original JPEG/PNG

### ISSUE THREAD

**Issue by ddur** [QROkes/webinoly#48]
It is easy to do, just take look at https://github.com/WordOps/WordOps/ repository.

Regards.

**Comment by QROkes** [comment]
WordPress 5.8 has been released a couple of days ago including native support for WebP, if you want to do it "conditionally" you can add your own custom Nginx rules to your server.

**Comment by ddur** [comment]
WordPress native WebP support is only for new uploads.
Many WordPress sites still have hundreds or thousands of JPEG/PNG images in Media Library.

I will rather move to [WordOps](https://wordops.net/), 

WordOps software is high quality, feature complete and  maintainers are kind and friendly people.

Thanks.

**Comment by QROkes** [comment]
**Just for the record: This user was blocked and his last comment removed!**

Remember, I do this entirely in my free time and without any expectations from the users except for being polite to me and each other.
