### ISSUE TITLE
File Permission reset in faster way

### ISSUE THREAD

**Issue by nhanledev** [QROkes/webinoly#49]
Hello,

I often run the `webinoly -server-reset` after changing my VPS specs, and notice that the first 2 lines in https://github.com/QROkes/webinoly/blob/master/lib/webin#L313 are too slow.

I suggest that we should change these from:
`sudo find /var/www ! -path "/var/www/\.*" -type d -exec chmod 755 {} \;`
`sudo find /var/www ! -path "/var/www/\.*" -type f -exec chmod 644 {} \;`

To
`sudo find /var/www ! -path "/var/www/\.*" -type d -print0 | sudo xargs -0 chmod 0755`
`sudo find /var/www ! -path "/var/www/\.*" -type f -print0 | sudo xargs -0 chmod 0644`

For example, my `/var/www` folder currently has 134,091 files
I put current commands of webinoly to `oldway.sh`, my suggested commands to `newway.sh` and ran a simple time benchmark.
The result is my suggested ones run much much faster.

![image](https://user-images.githubusercontent.com/28459250/131978380-ffa5a864-d8d3-49de-87ff-da741902be96.png)

**Comment by QROkes** [comment]
Thanks @nhanledev I will test it and it will be scheduled for v1.16.1 release.

**Comment by QROkes** [comment]
Webinoly v1.16.2 has been released!
Can you please confirm that this improvement has been implemented correctly?
Thanks @nhanledev

**Comment by nhanledev** [comment]
Hello,

I checked the source code, and ran `webinoly -server-reset` on my development box. The reset progress is improved and file permissions are correctly reset.

Thank you so much for the update!
