### ISSUE TITLE
When webinoly has been updated. Upload wordpress  "Please choose a file". 

### ISSUE THREAD

**Issue by ibarreda** [QROkes/webinoly#52]
Scenario 1. 

Running command "webinoly -verify" alerts of new version , with "-update" it updates.  Apparently it works, but when going to upload a plugin or theme from the desktop it shows the error "Please choose a file". 

Scenario 2. 

A test server ubuntu 20.04 is installed and webinoly is installed, with the latest version a test wordpress is installed and again the same thing happens "Please choose a file" when trying to upload a plugin or theme. 

I understand that it will not be a huge problem, something related to permissions or maybe a change in the code. 

In the meantime I have restored the old backup and will not update the rest of the servers until I can solve it.

**Comment by ibarreda** [comment]
Install webinoly and adjust the maximum load and user auth, we are talking about a configuration that before upgrading works without altering any of the settings. 

Thank you very much for your time in creating a solid solution, Cristhian. I am considering during 2022 to make a significant donation to the project.

**Comment by QROkes** [comment]
> Install webinoly and adjust the maximum load and user auth, we are talking about a configuration that before upgrading works without altering any of the settings.

Sorry, if I'm not understanding your issue. Did you solve this issue after adjusting these two settings?
Can you please share the details to try to reproduce this issue?

**Comment by ibarreda** [comment]
I mean I haven't touched anything, I just updated a server without any modifications and tried a clean installation in other server. In both cases the error appeared in wordpress when trying to upload a plugin/theme from the browser.

**Comment by wolerine** [comment]
This issue occurs when uploading any file (theme,plugin,etc) from WP panel.
After upload finishes wp gives "Please choose a file" error.

I have tried both fresh installed server and also updated server from previous version of Webinoly. Got the same error in both situations.

**Comment by QROkes** [comment]
Can you check in your server logs for a clue?

**Comment by wolerine** [comment]
Error log shows such thing:

`2022/01/12 18:52:24 [error] 143407#143407: *58075 FastCGI sent in stderr: "PHP message: PHP Warning:  Maximum number of allowable file uploads has been exceeded in Unknown on line 0" while reading response header from upstream, client: 31.155.202.32, server: XXX.com.tr, request: "POST /wp-admin/update.php?action=upload-plugin HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "www.XXX.com.tr", referrer: "https://www.XXX.com.tr/wp-admin/plugin-install.php"
`

I have checked PHPinfo and upload limit shows 100MB. I have not changed any values.
I was trying to upload a file which was 8MB at all.

**Comment by QROkes** [comment]
Webinoly v1.16.1 has been released right now as a HotFix for this issue.
Please, update to this new version and then do PHP reset: `sudo webinoly -server-reset=php`

Confirm if it works, please!

**Comment by wolerine** [comment]
Thank you for the update.
v1.16.1 solved the issue.
