### ISSUE TITLE
Allow multi-users support

### ISSUE THREAD

**Issue by starnetwork** [QROkes/webinoly#55]
Hi,
I suggest to add multiple users support
each website can be created under new random user and group to avoid any security Leakage between sites
and also option to create per-site sftp account

thanks!

**Comment by QROkes** [comment]
Please, read the documentation before opening new issues!
This topic has been discussed several times before.

**Comment by starnetwork** [comment]
thanks for that, I will looking for it.

**Comment by starnetwork** [comment]
Hi,
I have comment the original post, can you please re-consider to open it?

thanks!

**Comment by QROkes** [comment]
After reading the original post there are only two options if you think we should reconsider it:

- You are using Nginx Plus (not free).
- Or you didn't really understand the original post's previous comments.

**Comment by starnetwork** [comment]
from what I know, it's can work also without Nginx Plus, example: https://serverfault.com/questions/370820/user-per-virtual-host-in-nginx
also, all most popular web hosting panels (cPanel / Plesk / DirectAdmin) and more... doing that and it's work well.

**Comment by QROkes** [comment]
Yes, there are maybe thousands or millions of that kind of cheap tutorials available.
Please, read more about Nginx Plus, the purge_cache module. **Believe me, you will need it!**

Some years ago this topic was included on our FAQ page to prevent this kind of discussion.
