### ISSUE TITLE
Allow json based nginx logs

### ISSUE THREAD

**Issue by starnetwork** [QROkes/webinoly#56]
please consider to add by default json log format for all new sites / sub-domains / pointers logs
example:
`log_format json_combined escape=json
  '{'
    '"time_local":"$time_local",'
    '"remote_addr":"$remote_addr",'
    '"remote_user":"$remote_user",'
    '"request":"$request",'
    '"status": "$status",'
    '"body_bytes_sent":"$body_bytes_sent",'
    '"request_time":"$request_time",'
    '"http_referrer":"$http_referer",'
    '"http_user_agent":"$http_user_agent"'
  '}';`

thanks!

**Comment by QROkes** [comment]
I don't really think that Webinoly should have an option for each possible configuration supported by Nginx. These kinds of things can be tuned up by each user according to their needs. But I will leave it open, to see if other users find it useful.
