### ISSUE TITLE
Getting this error when trying to make a new wordpress site on Ubuntu 22.04

### ISSUE THREAD

**Issue by mendelsphotography** [QROkes/webinoly#57]
140698147750336:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:119:filename(libproviders.so): libproviders.so: cannot open shared object file: No such file or directory
140698147750336:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:162:
140698147750336:error:0E07506E:configuration file routines:module_load_dso:error loading dso:crypto/conf/conf_mod.c:224:module=providers, path=providers
140698147750336:error:0E076071:configuration file routines:module_run:unknown module name:crypto/conf/conf_mod.c:165:module=providers

**Comment by QROkes** [comment]
**Please, read the documentation before opening a new issue!**
Ubuntu Jammy is still not supported.

**Comment by mendelsphotography** [comment]
oh sorry

**Comment by mendelsphotography** [comment]
is there anything I can do about that or is going to be supported at some point?

**Comment by QROkes** [comment]
All these kinds of things are frequently posted on our social media, also we send this info in our newsletter. **Please, read the docs and all our official channels before asking.**

**Comment by mendelsphotography** [comment]
ok thanks did not think it would be on there as this resulted from OpenSSL issue

**Comment by mendelsphotography** [comment]
thanks for now updating and supporting 22.04
