### ISSUE TITLE
Custom nginx conf not working

### ISSUE THREAD

**Issue by hj-collab** [QROkes/webinoly#60]
Hi,

Thank you for your hard work. I have created an custom nginx conf file alled rp-nginx.conf in /var/www/mysite/ with the following code.

`
location ~* ^.+\.(zip|gz|bzip2|7z)$ {
	deny all;
	access_log off;
	log_not_found off;
}
`
I am still able to load zip files from www.mysite.com/example.zip. Any idea where I am going wrong?

**Comment by QROkes** [comment]
Here is for issues, not a support forum!
