### ISSUE TITLE
Webinoly -update > BASH Shell is required!

### ISSUE THREAD

**Issue by TheSoulrester** [QROkes/webinoly#61]
Hi, 

yesterday I wanted to update webinoly - but it says that Bash Shell is required!
![image](https://user-images.githubusercontent.com/7083599/179667367-40ea6c3e-af6e-4c55-bf8e-51be22021def.png)

I executed this command as root, my root has Bash Shell rights
![image](https://user-images.githubusercontent.com/7083599/179667527-5cdd6270-953b-4317-95e7-bce371532a9b.png)

The installed version is v1.16.3

I also cannot reinstall webinoly with `wget -qO weby qrok.es/wy && sudo bash weby`
It also says that BASH Shell is required!

Can anyone help me? THank you :)

**Comment by QROkes** [comment]
**Duplicate:** #53 

That's because you're using an interactive shell different than Bash.
A good search is important to prevent duplicate questions. _(duplicate questions are annoying)_
