### ISSUE TITLE
Webinoly and Ubuntu 22.04 Compitability

### ISSUE THREAD

**Issue by starnetwork** [QROkes/webinoly#62]
Hi,
Just installed Webinoly on Ubuntu 22.04 and getting this errors via installation:
`Nginx has been successfully Optimized by Webinoly!
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
touch: cannot touch '/var/www/22222/htdocs/nginx_status': No such file or directory
touch: cannot touch '/var/www/22222/htdocs/robots.txt': No such file or directory
/opt/webinoly/lib/install: line 462: /var/www/22222/htdocs/robots.txt: No such file or directory
chmod: cannot access '/var/www/22222/htdocs/robots.txt': No such file or directory
chown: cannot access '/var/www/22222/htdocs': No such file or directory
certbot 1.29.0 from Certbot Project (certbot-eff✓) installed
`

after that:
`PHP has been successfully Optimized by Webinoly!
touch: cannot touch '/var/www/22222/htdocs/ping': No such file or directory
touch: cannot touch '/var/www/22222/htdocs/status': No such file or directory
Reading package lists... Done
`

and at the end:
BASH Shell is required! (sudowebinoly-login-www-data=on)
and bash is working.

**Comment by QROkes** [comment]
Reporting issues this way is totally useless if you cannot provide details.
