### ISSUE TITLE
Overzealous bash verification

### ISSUE THREAD

**Issue by mwt** [QROkes/webinoly#63]
Webinoly attempts to run sub commands at times. When it does, it consistently fails the "bash check" and exits. For example, if you try to follow the homepage guide to install wordpress, webinoly will attempt to install php, when it does, I get the following error:

```sh
> site example.com -wp
```
```
+ PHP Not Found!
Do you want to install it now? [y/N]? 

BASH Shell is required! (sudostack-php)
```

What is happening is that stack is checking to see if bash is being used by checking "$0". Because this is a sub-command, this returns the command that was run by the parent script, `sudo stack -php`. This can be partially fixed by running `sudo stack -php` directly. However, this also returns an error once the first subcommand is run:

```sh
> sudo stack -php
```
```
...
Memcached has been installed successfully! 
BASH Shell is required! (sudowebinoly-verify=critical)
```

Again, webinoly is trying to run `sudo webinoly -verify=critical`. However, this fails because the zero input is not bash. It's `sudowebinoly-verify=critical`.

I'm not really sure what to do here. **Obviously, I am running bash.** I'm not trying to do anything weird here. I followed the instructions from the main page. I've tried this in several different VMs of Ubuntu Jammy and got the same result.

**Comment by QROkes** [comment]
Yes, thanks for reporting this issue!
It's only happening in the new Ubuntu 22.04 and with some specific cloud providers.

It will be fixed very soon!

**Comment by starnetwork** [comment]
> Yes, thanks for reporting this issue! It's only happening in the new Ubuntu 22.04 and with some specific cloud providers.
> 
> It will be fixed very soon!

also reported here: https://github.com/QROkes/webinoly/issues/62

**Comment by QROkes** [comment]
Webinoly v1.16.7 is released now!
Please, confirm that this issue is fixed.

**Comment by starnetwork** [comment]
look like it's work, thanks!
