### ISSUE TITLE
[Feature Request] Ability to use same media library between prod and staging

### ISSUE THREAD

**Issue by hj-collab** [QROkes/webinoly#64]
Slick Stack allows users to share media library between prod and staging. It's good for servers with less disk space. Take a look. https://github.com/littlebizzy/slickstack

"SlickStack staging sites mirror media files from production to save time and disk space, there was confusion about uploading files in staging sites (we were planning to disable uploading function)... now, we have successfully tested a better solution with Linux symlinks! WordPress now functions normally in staging and media files can be uploaded as per normal, but the files are sent to production /uploads/ by Linux... users no longer confused, and previous advantages preserved 🥳"

**Comment by QROkes** [comment]
Out of the scope of this project!
