### ISSUE TITLE
[Feature Request] Ability to modify following stuff in webinoly.conf via commandline

### ISSUE THREAD

**Issue by hj-collab** [QROkes/webinoly#65]
I am not able to modify the following stuff using sudo webinoly -example.

xmlrpc
header-cache-control
header-csp
header-hsts
header-permissions
header-referrer

**Comment by QROkes** [comment]
Please, read the documentation!

**Comment by QROkes** [comment]
That option is already included!
You can modify any variable in the conf file directly from the command line.
Just take a look at the docs!

**Comment by milicodex** [comment]
@hj-collab **I have not tested this** but reading the documentation about the webinoly config file I would try this command

sudo webinoly -dynvar=xmlrpc -value=blocked

You can read this info at the very end of the configuration file documentation here
https://webinoly.com/documentation/webinolys/#server-settings

Another thing that you can do is edit the config file with nano without the need to edit and reupload a file, as you mentioned in your second message here.
Like this

sudo nano /opt/webinoly/webinoly.conf

For the headers part I don't think you can do it with a command anymore, check here
https://webinoly.com/documentation/webinolys/#headers
