### ISSUE TITLE
[Feature Request] Make -max=n parameter work for non db backups

### ISSUE THREAD

**Issue by hj-collab** [QROkes/webinoly#67]
Hi @QROkes,

I use the following command to set a max limit for db backups and it works like charm. Thank you!

sudo webinoly -backup=local -wp=sitename.com -destination=/root/dbbackup/sitename -max=7

But the same -max=n does not work for non db backups
sudo webinoly -backup=local -export=sitename.com -skip-db -destination=/root/filesbackup/sitename -max=7

It crosses the max limit and does not delete the oldest backup. Any way to get around this? I want to use file backups with a max limit.

**Comment by QROkes** [comment]
I really appreciate your interest in Webinoly, but please, stop opening new "issues" for this kind of request. [The guidelines in our community forum](https://webinoly.com/support/849/this-is-not-a-support-forum), also apply here.
