### ISSUE TITLE
Lost sysctl.conf after upgrading

### ISSUE THREAD

**Issue by nhanledev** [QROkes/webinoly#68]
I upgrade some of my VPS from `1.16` to `1.17` and the custom webinoly optimization inside the file `/etc/sysctl.conf` is purged to default. 

The file `/etc/opt/webinoly/webinoly.conf` still shows the `linux-optim:true`

What to expect: Optimized configuration inside `/etc/sysctl.conf` should be kept or updated.

**Comment by QROkes** [comment]
Location was changed.
