### ISSUE TITLE
Cannot register on Webinoly support

### ISSUE THREAD

**Issue by Zeplish** [QROkes/webinoly#70]
The antispam is not working. I tried on Chrome, Brave, Safari and even using a VPN but nothing works. Please look into it.

<img width="1279" alt="Screenshot 2023-01-30 at 8 23 12 AM" src="https://user-images.githubusercontent.com/87347147/215377891-3000c775-94ee-4939-9029-e4bf939869af.png">

**Comment by QROkes** [comment]
Your IP is blacklisted in some SPAM databases:

- https://api.stopforumspam.org/api?email[]=hello@zeplish.com&ip[]=122.162.146.255
- https://cleantalk.org/blacklists/122.162.146.255

Try using a different network!

**Comment by Zeplish** [comment]
Ok. Thanks.
