### ISSUE TITLE
How to disable domain forwarding?

### ISSUE THREAD

**Issue by Zeplish** [QROkes/webinoly#71]
I forwarded a domain **abc.com** to **xyz.com** using the parameter -forward=xyz.com
Now I want to disable this and bring abc.com back.
I tried looking inside every config file in the server but there is no mention of xyz.com anywhere which I could remove. There is no command in the webinoly documentation as well.

Please guide. Thanks.

**Comment by QROkes** [comment]
**Please, read the documentation!** And please, don't open an issue, for support requests.
