### ISSUE TITLE
Sitemaps failing in WordPress

### ISSUE THREAD

**Issue by hiepsocool** [QROkes/webinoly#75]
Hello BQT Webinoly
I have updated to the latest version v1.17.2. But my sitemap is still failing. Specifically my sitemap is: https://chieuta.com/sitemap_index.xml .
I use Yoast SEO to create my sitemap.
Got a 404 Not Found error, and I can't find the cause to fix it.
Can you help me?
Thank you for viewing the topic.

**Comment by QROkes** [comment]
Your sitemap is working fine, I don't see any problems!
