### ISSUE TITLE
Issue Importing Site on Ubuntu 22

### ISSUE THREAD

**Issue by mikesyph** [QROkes/webinoly#79]
In regards to this post: [Issure restoring website to NEW server, from ubuntu 20.04 to 22.04](https://webinoly.com/support/9167/issure-restoring-website-to-new-server-from-ubuntu-20-04-to-22)]

There seems to be an issue importing sites. The error reads:

```
grep: <examplefilename>: binary file matches
[ERROR] File not found or empty!
```

**Comment by QROkes** [comment]
Opening new tickets for the same issue is completely annoying!

**Comment by mikesyph** [comment]
I apologize. I thought since it seems to be more of a formal bug, this would be the best place to put it, rather than the discussion forum. My intention was to be most helpful to you, not annoy. Sorry about that
