### ISSUE TITLE
sudo webinoly -db-import 

### ISSUE THREAD

**Issue by daryltavernor** [QROkes/webinoly#82]
root@ubuntu-16gb-nbg1-1:~# sudo webinoly -db-import
SQL file path to import: /var/sqlmigrate/dtrebgjgg_wp1.sql
ERROR 1046 (3D000) at line 22: No database selected

How do I flag which database to use?

**Comment by QROkes** [comment]
The "-db-import" is for databases, not for tables.
That error occurs when you have exported just some tables and not the whole database.

**Comment by daryltavernor** [comment]
I'm try to import a db for a migration from cpanel. Is there a different db migration utility to use?
